- name: install docker
  hosts: lostembos
  become: true
  tasks: 
   - name: 
     ansible.builtin.dnf:
      name: docker
      state: latest 

   - name: add user mar to the group docker
     user:
      name: mar
      group: docker
      state: present

   - name: make sure docker is runing 
     systemd: 
      name: docker
      state: started
      enabled: true